import type { KBTemplate } from "@/lib/pharmacologyKnowledgeBase";

const hr = {
  confidence: "medium" as const,
  source_type: "harm reduction" as const,
  needs_review: true,
  requires_clinical_review: true,
  review_status: "template / revisão obrigatória",
  source_notes:
    "Template estrutural para monitoramento clínico e redução de danos. Inspirado em literatura farmacológica, bulas quando aplicável e fontes abertas de harm reduction como PsychonautWiki/Erowid/relatos observacionais. Não orienta uso recreativo, dose ilícita ou método de consumo.",
};

const rx = {
  confidence: "medium" as const,
  source_type: "estrutural" as const,
  needs_review: true,
  requires_clinical_review: true,
  review_status: "template / revisão obrigatória",
  source_notes:
    "Template farmacológico estrutural. Revisão clínica obrigatória. Curvas relativas 0–100, não séricas. Conferir bula, diretrizes e contexto brasileiro antes de decisão clínica.",
};

function oralForm(name: string, curve: string, onset: [number, number, string], peak: [number, number, string], duration: [number, number, string], halfLife?: [number, number, string]): any {
  return {
    formulation_name: name,
    formulation_type: name,
    route: "oral",
    curve_model: curve,
    onset_min_value: onset[0], onset_max_value: onset[1], onset_unit: onset[2],
    peak_min_value: peak[0], peak_max_value: peak[1], peak_unit: peak[2],
    duration_min_value: duration[0], duration_max_value: duration[1], duration_unit: duration[2],
    half_life_min_value: halfLife?.[0], half_life_max_value: halfLife?.[1], half_life_unit: halfLife?.[2],
    has_tail: true,
    tail_min_value: duration[1], tail_max_value: halfLife ? Math.max(duration[1], halfLife[1] * 2) : duration[1] * 2,
    tail_unit: duration[2] === "dias" ? "dias" : "horas",
    is_default: true,
    notes: "Template de formulação estrutural; ajustar por produto, paciente e literatura revisada.",
  };
}

function mkMedication(params: Partial<KBTemplate> & Pick<KBTemplate, "name">): KBTemplate {
  return {
    ...rx,
    substance_type: "medicamento",
    controlled_substance: true,
    requires_prescription: true,
    evidence_level: "variável conforme indicação; revisar fonte primária",
    default_route: "oral",
    available_routes: ["oral"],
    dose_unit_default: "mg",
    default_dose_unit: "mg",
    ...params,
  };
}

function mkHarm(params: Partial<KBTemplate> & Pick<KBTemplate, "name">): KBTemplate {
  return {
    ...hr,
    substance_type: "substância recreativa",
    evidence_level: "misto: farmacologia formal + toxicologia + relatos observacionais/harm reduction",
    default_route: "variável",
    available_routes: ["oral", "inalada/fumada", "intranasal", "sublingual", "injetável/IV"],
    ...params,
  };
}

export const EXPANDED_KNOWLEDGE_TEMPLATES: KBTemplate[] = [
  mkMedication({
    name: "Venlafaxina XR",
    generic_name: "cloridrato de venlafaxina",
    normalized_key: "venlafaxina_xr",
    match: ["venlafaxina", "effexor", "venlift", "alenthus", "venlaxin"],
    brand_names: ["Efexor XR", "Venlift OD", "Alenthus XR"],
    pharmacological_class: "IRSN / antidepressivo dual serotonina-noradrenalina",
    clinical_category: "depressão / ansiedade / energia / dor",
    mechanism_summary: "Inibe SERT e, em doses maiores, NET; metabólito ativo O-desmetilvenlafaxina.",
    mechanism_expanded: "Antidepressivo serotoninérgico-noradrenérgico com curva de liberação prolongada. Em dose baixa predomina SERT; com aumento de dose cresce componente NET. Metabolismo principalmente CYP2D6 para desvenlafaxina.",
    neurotransmitter_effects: { serotonin: 80, noradrenalina: 55, dopamina_pfc_indireta: 15 },
    circuit_effects: { humor: 75, ansiedade: 55, dor: 35, ativacao: 45 },
    cyp_substrate: ["CYP2D6", "CYP3A4"],
    active_metabolites: ["desvenlafaxina"],
    has_steady_state: true, steady_state_min_value: 3, steady_state_max_value: 5, steady_state_unit: "dias",
    half_life_min_value: 10, half_life_max_value: 15, half_life_unit: "horas",
    formulations: [oralForm("Cápsula XR", "XR / steady-state diário", [2, 6, "horas"], [5, 8, "horas"], [24, 24, "horas"], [10, 15, "horas"])],
    clinical_effect_profile: { antidepressivo: 75, ansiolitico: 55, energia: 45, dor: 35 },
    adverse_effect_profile: { nausea: 55, insomnia: 45, pa_fc: 55, withdrawal: 70, sexual: 55 },
    monitoring_profile: ["PA/FC", "sono", "ansiedade/ativação", "sintomas de descontinuação", "risco serotoninérgico"],
  }),
  mkMedication({
    name: "Vilazodona",
    generic_name: "cloridrato de vilazodona",
    normalized_key: "vilazodona",
    match: ["viibryd", "vilazodone", "vilazodona"],
    pharmacological_class: "ISRS + agonista parcial 5-HT1A",
    clinical_category: "depressão / ansiedade depressiva",
    mechanism_summary: "Inibe SERT e atua como agonista parcial 5-HT1A; antidepressivo serotoninérgico multimodal simples.",
    receptor_profile: [{ target: "5-HT1A", action_type: "agonista parcial", clinical_relevance: "ansiedade/humor" }, { target: "SERT", action_type: "inibidor", clinical_relevance: "serotonina" }],
    cyp_substrate: ["CYP3A4"],
    formulations: [oralForm("Comprimido oral com alimento", "steady-state serotoninérgico", [2, 6, "horas"], [4, 5, "horas"], [24, 24, "horas"], [23, 26, "horas"])],
    has_steady_state: true, steady_state_min_value: 5, steady_state_max_value: 7, steady_state_unit: "dias",
    food_effect_notes: "Absorção clinicamente dependente de alimento; registrar se tomado com refeição.",
    adverse_effect_profile: { gastrointestinal: 70, insomnia: 35, serotoninergic: 50, sexual: 35 },
  }),
  mkMedication({ name: "Guanfacina", generic_name: "cloridrato de guanfacina", normalized_key: "guanfacina", match: ["intuniv", "guanfacine"], pharmacological_class: "agonista alfa-2A adrenérgico", clinical_category: "TDAH / impulsividade / hiperreatividade", mechanism_summary: "Agonista alfa-2A pré-frontal; reduz ruído noradrenérgico e impulsividade.", neurotransmitter_effects: { noradrenalina_ruido: -55 }, circuit_effects: { pfc: 55, impulsividade: 55, hiperalerta: 45 }, formulations: [oralForm("Comprimido ER", "alfa-2A ER / steady-state", [2, 5, "horas"], [5, 8, "horas"], [24, 24, "horas"], [14, 18, "horas"])], has_steady_state: true, steady_state_min_value: 4, steady_state_max_value: 5, steady_state_unit: "dias", adverse_effect_profile: { sedacao: 55, hipotensao: 50, bradicardia: 35, rebote: 55 } }),
  mkMedication({ name: "Modafinila", generic_name: "modafinila", normalized_key: "modafinila", match: ["provigil", "stavigile", "modafinil"], pharmacological_class: "promotor de vigília / DAT fraco-atípico", clinical_category: "vigília / fadiga / sonolência", mechanism_summary: "Promove vigília por redes histaminérgicas/orexinérgicas/catecolaminérgicas; menor perfil euforizante que anfetaminas, mas não é neutro.", cyp_substrate: ["CYP3A4"], cyp_inducer: ["CYP3A4"], cyp_inhibitor: ["CYP2C19"], formulations: [oralForm("Comprimido oral", "vigília longa", [30, 90, "minutos"], [2, 4, "horas"], [10, 15, "horas"], [12, 15, "horas"])], clinical_effect_profile: { vigilia: 85, foco: 45, energia: 60 }, adverse_effect_profile: { insomnia: 60, anxiety: 35, headache: 45, rash: 10 }, abuse_risk_level: "baixo" }),
  mkMedication({ name: "Armodafinila", generic_name: "armodafinila", normalized_key: "armodafinila", match: ["nuvigil", "armodafinil"], pharmacological_class: "promotor de vigília / R-enantiômero modafinila", clinical_category: "vigília / fadiga", mechanism_summary: "R-enantiômero da modafinila, duração subjetiva mais longa em alguns pacientes.", formulations: [oralForm("Comprimido oral", "vigília longa", [45, 120, "minutos"], [2, 6, "horas"], [12, 16, "horas"], [13, 16, "horas"])], adverse_effect_profile: { insomnia: 65, anxiety: 35, headache: 45 }, abuse_risk_level: "baixo" }),
  mkMedication({ name: "Desvenlafaxina", generic_name: "succinato de desvenlafaxina", normalized_key: "desvenlafaxina", match: ["pristiq", "elixir", "desve", "desvenlafaxine"], pharmacological_class: "IRSN", clinical_category: "depressão / energia / ansiedade", mechanism_summary: "Metabólito ativo da venlafaxina; inibe SERT/NET, com menor dependência CYP2D6.", formulations: [oralForm("Comprimido ER", "ER / steady-state diário", [2, 6, "horas"], [6, 8, "horas"], [24, 24, "horas"], [11, 14, "horas"])], has_steady_state: true, steady_state_min_value: 4, steady_state_max_value: 5, steady_state_unit: "dias", adverse_effect_profile: { pa_fc: 45, insomnia: 40, nausea: 45, withdrawal: 55 } }),
  mkMedication({ name: "Fluvoxamina", generic_name: "maleato de fluvoxamina", normalized_key: "fluvoxamina", match: ["luvox", "fluvoxamine"], pharmacological_class: "ISRS / inibidor CYP1A2 e CYP2C19", clinical_category: "TOC / ansiedade / depressão", mechanism_summary: "ISRS com inibição relevante de CYP1A2/2C19 e interações numerosas; útil em TOC/ruminação, mas farmacocineticamente barulhento.", cyp_inhibitor: ["CYP1A2", "CYP2C19", "CYP3A4"], formulations: [oralForm("Comprimido oral", "ISRS meia-vida intermediária", [2, 6, "horas"], [3, 8, "horas"], [24, 24, "horas"], [15, 22, "horas"])], adverse_effect_profile: { nausea: 55, sedation: 35, interactions: 80, sexual: 45 } }),
  mkMedication({ name: "Paroxetina", generic_name: "cloridrato de paroxetina", normalized_key: "paroxetina", match: ["paxil", "aropax", "paroxetine"], pharmacological_class: "ISRS / inibidor forte CYP2D6", clinical_category: "depressão / ansiedade", mechanism_summary: "ISRS com carga anticolinérgica relativa e forte inibição CYP2D6; maior risco de descontinuação e disfunção sexual.", cyp_inhibitor: ["CYP2D6"], formulations: [oralForm("Comprimido oral", "ISRS meia-vida curta", [2, 6, "horas"], [5, 8, "horas"], [24, 24, "horas"], [18, 24, "horas"])], adverse_effect_profile: { withdrawal: 80, sexual: 65, sedation: 40, weight: 35, cyp2d6: 90 } }),
  mkMedication({ name: "Clomipramina", generic_name: "clomipramina", normalized_key: "clomipramina", match: ["anafranil", "clomipramine"], pharmacological_class: "tricíclico serotoninérgico", clinical_category: "TOC / depressão / ansiedade", mechanism_summary: "TCA com potente SERT e carga anticolinérgica/cardiotóxica; interações e ECG importam.", cyp_substrate: ["CYP2D6", "CYP2C19", "CYP3A4"], formulations: [oralForm("Comprimido/cápsula oral", "TCA steady-state", [2, 6, "horas"], [2, 6, "horas"], [24, 24, "horas"], [20, 40, "horas"])], adverse_effect_profile: { anticholinergic: 75, qt: 60, seizure: 45, sexual: 55, sedation: 50 } }),
  mkMedication({ name: "Topiramato", generic_name: "topiramato", normalized_key: "topiramato", match: ["topamax", "topiramate"], pharmacological_class: "anticonvulsivante / modulador glutamato-GABA", clinical_category: "impulsividade / enxaqueca / compulsão / TUS", mechanism_summary: "Modula canais de sódio, AMPA/kainato, GABA-A e anidrase carbônica; pode reduzir impulsos/craving, mas cobra preço cognitivo.", formulations: [oralForm("Comprimido oral", "steady-state anticonvulsivante", [2, 6, "horas"], [2, 4, "horas"], [24, 24, "horas"], [19, 25, "horas"])], adverse_effect_profile: { cognitive: 75, paresthesia: 55, appetite_loss: 65, kidney_stone: 25, acidosis: 25 }, clinical_effect_profile: { craving: 45, impulsividade: 45, weight_loss: 60 } }),
  mkMedication({ name: "Carbamazepina", generic_name: "carbamazepina", normalized_key: "carbamazepina", match: ["tegretol", "carbamazepine"], pharmacological_class: "anticonvulsivante / bloqueador canais de sódio / indutor CYP", clinical_category: "epilepsia / humor / impulsividade", mechanism_summary: "Bloqueia canais de sódio; forte indutor CYP3A4/UGT, com autoindução e muitas interações.", cyp_inducer: ["CYP3A4", "CYP2C9", "CYP1A2", "UGT"], formulations: [oralForm("Comprimido oral", "autoindução / steady-state", [2, 6, "horas"], [4, 8, "horas"], [12, 24, "horas"], [12, 17, "horas"])], adverse_effect_profile: { rash: 40, hyponatremia: 35, interactions: 95, sedation: 40, hematologic: 25 } }),
  mkMedication({ name: "Oxcarbazepina", generic_name: "oxcarbazepina", normalized_key: "oxcarbazepina", match: ["trileptal", "oxcarbazepine"], pharmacological_class: "anticonvulsivante / bloqueador canais de sódio", clinical_category: "epilepsia / labilidade / impulsividade", mechanism_summary: "Pró-fármaco para MHD; menos indutor que carbamazepina, mas hiponatremia é relevante.", formulations: [oralForm("Comprimido oral", "metabólito ativo MHD", [2, 6, "horas"], [4, 6, "horas"], [12, 24, "horas"], [8, 15, "horas"])], active_metabolites: ["MHD"], adverse_effect_profile: { hyponatremia: 60, dizziness: 45, sedation: 35, rash: 25 } }),
  mkMedication({ name: "Diazepam", generic_name: "diazepam", normalized_key: "diazepam", match: ["valium"], pharmacological_class: "benzodiazepínico / GABA-A PAM", clinical_category: "ansiolítico / abstinência / anticonvulsivante", mechanism_summary: "BZD de longa duração com metabólitos ativos; alto risco com opioides/álcool.", cyp_substrate: ["CYP2C19", "CYP3A4"], active_metabolites: ["desmetildiazepam", "oxazepam", "temazepam"], formulations: [oralForm("Comprimido oral", "BZD longo com metabólitos ativos", [15, 60, "minutos"], [1, 2, "horas"], [8, 24, "horas"], [20, 80, "horas"])], abuse_risk_level: "alto", respiratory_depression_risk_level: "alto", withdrawal_profile: { score: 90, notes: "risco importante de abstinência se uso continuado" } }),
  mkMedication({ name: "Alprazolam", generic_name: "alprazolam", normalized_key: "alprazolam", match: ["frontal", "xanax", "alpraz"], pharmacological_class: "benzodiazepínico / GABA-A PAM", clinical_category: "ansiolítico", mechanism_summary: "BZD de início rápido, reforço alto e retirada difícil; risco alto em TUS.", cyp_substrate: ["CYP3A4"], formulations: [oralForm("Comprimido oral", "BZD rápido/intermediário", [15, 45, "minutos"], [1, 2, "horas"], [4, 8, "horas"], [10, 16, "horas"])], abuse_risk_level: "muito alto", withdrawal_profile: { score: 95, notes: "alto rebote ansioso e abstinência" } }),
  mkMedication({ name: "Zolpidem", generic_name: "zolpidem", normalized_key: "zolpidem", match: ["stilnox", "ambien"], pharmacological_class: "hipnótico Z / GABA-A alfa1", clinical_category: "insônia", mechanism_summary: "Hipnótico não-BZD, reforço e comportamentos complexos do sono possíveis; monitorar uso problemático.", formulations: [oralForm("Comprimido oral IR", "hipnótico curto", [15, 30, "minutos"], [0.5, 1.5, "horas"], [4, 6, "horas"], [2, 3, "horas"])], abuse_risk_level: "moderado", adverse_effect_profile: { amnesia: 55, parasomnia: 45, falls: 35, dependence: 45 } }),
  mkMedication({ name: "Prometazina", generic_name: "prometazina", normalized_key: "prometazina", match: ["fenergan", "promethazine"], pharmacological_class: "anti-histamínico H1 / anticolinérgico", clinical_category: "sedação / náusea / alergia", mechanism_summary: "H1 antagonista sedativo com carga anticolinérgica; pode piorar cognição e ressaca.", formulations: [oralForm("Comprimido/gotas oral", "sedativo anti-histamínico", [20, 60, "minutos"], [2, 4, "horas"], [6, 12, "horas"], [10, 19, "horas"])], adverse_effect_profile: { sedation: 80, anticholinergic: 70, cognitive: 60, qt: 25 } }),
  mkMedication({ name: "Hidroxizina", generic_name: "hidroxizina", normalized_key: "hidroxizina", match: ["hixizine", "atarax", "hydroxyzine"], pharmacological_class: "anti-histamínico H1 sedativo", clinical_category: "ansiedade / prurido / sono", mechanism_summary: "H1 antagonista ansiolítico-sedativo; sem abuso clássico, mas ressaca/cognição importam.", formulations: [oralForm("Comprimido/solução oral", "sedativo H1", [20, 60, "minutos"], [2, 4, "horas"], [6, 12, "horas"], [14, 25, "horas"])], adverse_effect_profile: { sedation: 70, anticholinergic: 45, qt: 25, cognitive: 35 } }),
  mkMedication({ name: "Propranolol", generic_name: "propranolol", normalized_key: "propranolol", match: ["inderal"], pharmacological_class: "betabloqueador não seletivo", clinical_category: "ansiedade autonômica / tremor / PA", mechanism_summary: "Bloqueia beta-1/beta-2; reduz tremor/taquicardia periférica sem tratar cognição ansiosa central diretamente.", formulations: [oralForm("Comprimido oral IR", "betabloqueador IR", [30, 60, "minutos"], [1, 2, "horas"], [4, 8, "horas"], [3, 6, "horas"])], adverse_effect_profile: { bradycardia: 50, fatigue: 45, bronchospasm: 35, depression_subjective: 20 } }),
  mkMedication({ name: "Metadona", generic_name: "metadona", normalized_key: "metadona", match: ["methadone"], pharmacological_class: "agonista opioide µ / NMDA", clinical_category: "TUS opioide / analgesia", mechanism_summary: "Agonista µ de meia-vida longa, útil em manutenção; QT, sedação e interação com BZD/álcool são críticos.", formulations: [oralForm("Solução/comprimido oral", "opioide longo / steady-state", [30, 60, "minutos"], [2, 4, "horas"], [24, 36, "horas"], [8, 59, "horas"])], respiratory_depression_risk_level: "muito alto", qt_risk_level: "moderado", abuse_risk_level: "alto", withdrawal_profile: { score: 95 } }),
  mkMedication({ name: "Buprenorfina", generic_name: "buprenorfina", normalized_key: "buprenorfina", match: ["suboxone", "subutex", "buprenorphine"], pharmacological_class: "agonista parcial µ / antagonista κ", clinical_category: "TUS opioide / analgesia", mechanism_summary: "Agonista parcial µ com teto respiratório relativo, alta afinidade e risco de precipitar abstinência se usado cedo demais após agonistas completos.", default_route: "sublingual", available_routes: ["sublingual", "transdérmica", "injetável"], formulations: [{ formulation_name: "Filme/comprimido sublingual", formulation_type: "sublingual", route: "sublingual", curve_model: "opioide parcial longa duração", onset_min_value: 30, onset_max_value: 90, onset_unit: "minutos", peak_min_value: 1, peak_max_value: 4, peak_unit: "horas", duration_min_value: 24, duration_max_value: 72, duration_unit: "horas", half_life_min_value: 24, half_life_max_value: 42, half_life_unit: "horas", has_tail: true, tail_min_value: 48, tail_max_value: 96, tail_unit: "horas", is_default: true }], respiratory_depression_risk_level: "alto", abuse_risk_level: "moderado" }),
  mkMedication({ name: "Naltrexona", generic_name: "naltrexona", normalized_key: "naltrexona", match: ["revia", "vivitrol", "naltrexone"], pharmacological_class: "antagonista opioide", clinical_category: "TUS álcool/opioide", mechanism_summary: "Antagonista opioide; bloqueia reforço opioide e reduz reforço alcoólico em alguns pacientes. Exige ausência de opioide para evitar abstinência precipitada.", formulations: [oralForm("Comprimido oral", "antagonista opioide diário", [1, 2, "horas"], [1, 2, "horas"], [24, 24, "horas"], [4, 13, "horas"])], hepatic_adjustment_notes: "Monitorar hepatograma; cautela em hepatopatia.", adverse_effect_profile: { nausea: 35, dysphoria: 20, hepatic: 30 } }),

  mkHarm({ name: "Nicotina", normalized_key: "nicotina", match: ["cigarro", "vape", "nicotine", "pod", "tabaco"], pharmacological_class: "agonista nicotínico nAChR", clinical_category: "substância lícita / dependência", mechanism_summary: "Agonista nicotínico com reforço dopaminérgico rápido; via altera onset drasticamente.", neurotransmitter_effects: { acetilcolina_nicotinica: 80, dopamina: 60, noradrenalina: 45 }, formulations: [{ formulation_name: "Inalada/fumada/vape", route: "inalada/fumada", curve_model: "onset rápido reforçador", onset_min_value: 5, onset_max_value: 60, onset_unit: "segundos", peak_min_value: 5, peak_max_value: 10, peak_unit: "minutos", duration_min_value: 1, duration_max_value: 2, duration_unit: "horas", half_life_min_value: 1, half_life_max_value: 2, half_life_unit: "horas", is_default: true }, { formulation_name: "Transdérmica", route: "transdérmica", curve_model: "liberação sustentada", onset_min_value: 1, onset_max_value: 4, onset_unit: "horas", peak_min_value: 6, peak_max_value: 12, peak_unit: "horas", duration_min_value: 16, duration_max_value: 24, duration_unit: "horas" }], abuse_risk_level: "muito alto", withdrawal_profile: { score: 85, notes: "irritabilidade, fissura, aumento apetite, insônia" } }),
  mkHarm({ name: "THC / Cannabis", normalized_key: "thc_cannabis", match: ["maconha", "cannabis", "thc", "haxixe", "hash", "weed", "skunk", "comestivel", "edible"], pharmacological_class: "agonista parcial CB1/CB2", clinical_category: "canabinoide / uso recreativo / medicinal em contextos específicos", mechanism_summary: "THC modula CB1, recompensa, percepção, memória e ansiedade; via fumada vs oral muda muito onset/duração.", neurotransmitter_effects: { endocanabinoide: 85, dopamina_indireta: 35, gaba_glutamato_modulados: 45 }, formulations: [{ formulation_name: "Inalada/fumada", route: "inalada/fumada", curve_model: "canabinoide inalado rápido", onset_min_value: 1, onset_max_value: 10, onset_unit: "minutos", peak_min_value: 15, peak_max_value: 30, peak_unit: "minutos", duration_min_value: 2, duration_max_value: 4, duration_unit: "horas", is_default: true }, { formulation_name: "Oral/comestível", route: "oral", curve_model: "canabinoide oral atraso longo", onset_min_value: 30, onset_max_value: 120, onset_unit: "minutos", peak_min_value: 2, peak_max_value: 4, peak_unit: "horas", duration_min_value: 6, duration_max_value: 12, duration_unit: "horas" }], psychosis_mania_risk_level: "moderado", abuse_risk_level: "moderado", adverse_effect_profile: { anxiety_paranoia: 60, memory: 65, amotivation: 35, tachycardia: 35 } }),
  mkHarm({ name: "MDMA", normalized_key: "mdma", match: ["ecstasy", "bala", "molly", "mandy", "md"], pharmacological_class: "entactógeno / liberador serotoninérgico", clinical_category: "substância ilícita / harm reduction", mechanism_summary: "Liberador serotoninérgico-noradrenérgico-dopaminérgico com risco de hipertermia, hiponatremia, síndrome serotoninérgica e queda pós-uso.", transporter_profile: [{ target: "SERT", action_type: "substrato/liberador" }, { target: "NET", action_type: "substrato/liberador" }, { target: "DAT", action_type: "substrato/liberador" }], formulations: [oralForm("Oral", "entactógeno oral", [30, 60, "minutos"], [1.5, 3, "horas"], [3, 6, "horas"], [7, 9, "horas"])], serotonin_syndrome_risk_level: "alto", abuse_risk_level: "moderado", adverse_effect_profile: { hyperthermia: 70, hyponatremia: 55, anxiety: 45, depression_after: 60, bruxism: 70 } }),
  mkHarm({ name: "Cetamina", normalized_key: "cetamina", match: ["ketamina", "ketamine", "special k", "keta"], pharmacological_class: "antagonista NMDA / dissociativo", clinical_category: "anestésico / antidepressivo em contextos específicos / harm reduction", mechanism_summary: "Antagonismo NMDA com dissociação, efeitos glutamatérgicos e potencial antidepressivo agudo em uso médico; risco urológico/cognitivo em uso repetido.", receptor_profile: [{ target: "NMDA", action_type: "antagonista", clinical_relevance: "dissociação/glutamato" }], formulations: [{ formulation_name: "Intranasal/insuflada", route: "intranasal", curve_model: "dissociativo intranasal", onset_min_value: 5, onset_max_value: 15, onset_unit: "minutos", peak_min_value: 20, peak_max_value: 60, peak_unit: "minutos", duration_min_value: 1, duration_max_value: 2, duration_unit: "horas", is_default: true }, { formulation_name: "IV médico", route: "IV", curve_model: "dissociativo IV rápido", onset_min_value: 30, onset_max_value: 120, onset_unit: "segundos", peak_min_value: 1, peak_max_value: 5, peak_unit: "minutos", duration_min_value: 30, duration_max_value: 60, duration_unit: "minutos" }], abuse_risk_level: "alto", adverse_effect_profile: { dissociation: 90, bp_hr: 45, nausea: 35, bladder: 60, cognition_chronic: 55 } }),
  mkHarm({ name: "LSD", normalized_key: "lsd", match: ["ácido", "acido", "lsd-25", "tabs", "papel"], pharmacological_class: "psicodélico serotoninérgico / agonista 5-HT2A", clinical_category: "substância ilícita / harm reduction", mechanism_summary: "Agonismo/partial agonism 5-HT2A com alterações perceptivas prolongadas; risco principal é psicológico/contextual, não depressão respiratória.", receptor_profile: [{ target: "5-HT2A", action_type: "agonista parcial", clinical_relevance: "psicodélico" }], formulations: [{ formulation_name: "Oral/sublingual", route: "oral/sublingual", curve_model: "psicodélico longa duração", onset_min_value: 30, onset_max_value: 90, onset_unit: "minutos", peak_min_value: 2, peak_max_value: 5, peak_unit: "horas", duration_min_value: 8, duration_max_value: 12, duration_unit: "horas", has_tail: true, tail_min_value: 12, tail_max_value: 24, tail_unit: "horas", is_default: true }], psychosis_mania_risk_level: "moderado", abuse_risk_level: "baixo", adverse_effect_profile: { panic: 60, insomnia: 65, psychosis_contextual: 35, hppd: 10 } }),
  mkHarm({ name: "Psilocibina", normalized_key: "psilocibina", match: ["cogumelo", "mushroom", "magic mushroom", "psilocybin", "psilocina"], pharmacological_class: "psicodélico serotoninérgico / pró-fármaco psilocina", clinical_category: "substância ilícita / pesquisa clínica / harm reduction", mechanism_summary: "Pró-fármaco de psilocina, agonismo 5-HT2A; duração intermediária e risco psicológico/contextual.", receptor_profile: [{ target: "5-HT2A", action_type: "agonista parcial" }], active_metabolites: ["psilocina"], formulations: [oralForm("Oral", "psicodélico oral", [20, 60, "minutos"], [1, 2, "horas"], [4, 6, "horas"], [2, 3, "horas"])], psychosis_mania_risk_level: "moderado", abuse_risk_level: "baixo", adverse_effect_profile: { nausea: 45, panic: 55, insomnia: 35 } }),
  mkHarm({ name: "Metanfetamina", normalized_key: "metanfetamina", match: ["meth", "crystal", "ice", "metanfeta"], pharmacological_class: "estimulante anfetamínico potente", clinical_category: "substância ilícita / alto risco", mechanism_summary: "Liberador potente de DA/NE, lipofílico, alto reforço e neurotoxicidade/contexto psicótico em uso repetido.", formulations: [{ formulation_name: "Inalada/fumada/intranasal/IV", route: "variável", curve_model: "estimulante potente alto reforço", onset_min_value: 0.1, onset_max_value: 20, onset_unit: "minutos", peak_min_value: 5, peak_max_value: 120, peak_unit: "minutos", duration_min_value: 6, duration_max_value: 12, duration_unit: "horas", half_life_min_value: 9, half_life_max_value: 12, half_life_unit: "horas", is_default: true }], abuse_risk_level: "muito alto", psychosis_mania_risk_level: "muito alto", cardiovascular_risk_level: "alto" }),
  mkHarm({ name: "Cocaína", normalized_key: "cocaina", match: ["coca", "cocaine", "crack", "pó", "po"], pharmacological_class: "inibidor DAT/NET/SERT + bloqueador canal de sódio", clinical_category: "estimulante ilícito / TUS", mechanism_summary: "Bloqueio de recaptação de DA/NE/5HT e canais de sódio; reforço rápido e risco cardiovascular/convulsivo.", formulations: [{ formulation_name: "Intranasal", route: "intranasal", curve_model: "estimulante curto alto reforço", onset_min_value: 1, onset_max_value: 5, onset_unit: "minutos", peak_min_value: 15, peak_max_value: 30, peak_unit: "minutos", duration_min_value: 0.5, duration_max_value: 1.5, duration_unit: "horas", is_default: true }, { formulation_name: "Fumada/crack", route: "inalada/fumada", curve_model: "onset ultrarrápido", onset_min_value: 5, onset_max_value: 30, onset_unit: "segundos", peak_min_value: 1, peak_max_value: 5, peak_unit: "minutos", duration_min_value: 0.2, duration_max_value: 0.5, duration_unit: "horas" }], abuse_risk_level: "muito alto", cardiovascular_risk_level: "muito alto", seizure_risk_level: "alto" }),
  mkHarm({ name: "Álcool", normalized_key: "alcool", match: ["alcool", "álcool", "etanol", "bebida"], pharmacological_class: "depressor SNC / GABA-NMDA", clinical_category: "substância lícita / TUS", mechanism_summary: "Modula GABA-A/NMDA e múltiplos sistemas; interage criticamente com BZD, opioides, sedativos e sono.", formulations: [{ formulation_name: "Oral", route: "oral", curve_model: "álcool oral absorção variável", onset_min_value: 10, onset_max_value: 30, onset_unit: "minutos", peak_min_value: 30, peak_max_value: 90, peak_unit: "minutos", duration_min_value: 2, duration_max_value: 8, duration_unit: "horas", is_default: true }], respiratory_depression_risk_level: "alto", abuse_risk_level: "alto", withdrawal_profile: { score: 85, notes: "abstinência pode ser grave/convulsiva em dependência" } }),
  mkHarm({ name: "Cafeína", normalized_key: "cafeina", match: ["café", "cafe", "energy drink", "energético", "guarana", "caffeine"], pharmacological_class: "antagonista adenosina / estimulante leve", clinical_category: "interferente lícito / sono / ansiedade", mechanism_summary: "Antagoniza adenosina, aumenta vigília e ruído autonômico; confunde leitura de estimulantes e sono.", formulations: [oralForm("Oral", "estimulante leve", [15, 45, "minutos"], [30, 90, "minutos"], [3, 6, "horas"], [3, 7, "horas"])], adverse_effect_profile: { insomnia: 70, anxiety: 55, tachycardia: 40, tremor: 45 }, abuse_risk_level: "moderado", withdrawal_profile: { score: 45, notes: "cefaleia, sonolência, irritabilidade" } }),
];
