
-- ============== SUBSTANCES ==============
ALTER TABLE public.substances
  ADD COLUMN IF NOT EXISTS generic_name text,
  ADD COLUMN IF NOT EXISTS reference_names text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS brand_names text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS synonyms text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS common_misspellings text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS substance_type text,
  ADD COLUMN IF NOT EXISTS legal_status text,
  ADD COLUMN IF NOT EXISTS therapeutic_areas text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS controlled_substance boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS requires_prescription boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS review_status text DEFAULT 'não revisada',
  ADD COLUMN IF NOT EXISTS primary_targets jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS secondary_targets jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS receptor_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS transporter_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS enzyme_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS neurotransmitter_effects jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS circuit_effects jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS clinical_effect_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS adverse_effect_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS abuse_liability_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS withdrawal_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS tolerance_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS dependence_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS pk_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS available_routes text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS available_formulations text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS default_formulation text,
  ADD COLUMN IF NOT EXISTS default_curve_model text,
  ADD COLUMN IF NOT EXISTS absorption_notes text,
  ADD COLUMN IF NOT EXISTS distribution_notes text,
  ADD COLUMN IF NOT EXISTS metabolism_notes text,
  ADD COLUMN IF NOT EXISTS elimination_notes text,
  ADD COLUMN IF NOT EXISTS protein_binding_percent numeric,
  ADD COLUMN IF NOT EXISTS bioavailability_min numeric,
  ADD COLUMN IF NOT EXISTS bioavailability_max numeric,
  ADD COLUMN IF NOT EXISTS half_life_min_value numeric,
  ADD COLUMN IF NOT EXISTS half_life_max_value numeric,
  ADD COLUMN IF NOT EXISTS half_life_unit text DEFAULT 'horas',
  ADD COLUMN IF NOT EXISTS active_metabolites text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS has_steady_state boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS steady_state_min_value numeric,
  ADD COLUMN IF NOT EXISTS steady_state_max_value numeric,
  ADD COLUMN IF NOT EXISTS steady_state_unit text DEFAULT 'dias',
  ADD COLUMN IF NOT EXISTS has_tail boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS tail_min_value numeric,
  ADD COLUMN IF NOT EXISTS tail_max_value numeric,
  ADD COLUMN IF NOT EXISTS tail_unit text DEFAULT 'horas',
  ADD COLUMN IF NOT EXISTS onset_min_value numeric,
  ADD COLUMN IF NOT EXISTS onset_max_value numeric,
  ADD COLUMN IF NOT EXISTS onset_unit text DEFAULT 'minutos',
  ADD COLUMN IF NOT EXISTS comeup_min_value numeric,
  ADD COLUMN IF NOT EXISTS comeup_max_value numeric,
  ADD COLUMN IF NOT EXISTS comeup_unit text DEFAULT 'minutos',
  ADD COLUMN IF NOT EXISTS peak_min_value numeric,
  ADD COLUMN IF NOT EXISTS peak_max_value numeric,
  ADD COLUMN IF NOT EXISTS peak_unit text DEFAULT 'horas',
  ADD COLUMN IF NOT EXISTS plateau_min_value numeric,
  ADD COLUMN IF NOT EXISTS plateau_max_value numeric,
  ADD COLUMN IF NOT EXISTS plateau_unit text DEFAULT 'horas',
  ADD COLUMN IF NOT EXISTS offset_min_value numeric,
  ADD COLUMN IF NOT EXISTS offset_max_value numeric,
  ADD COLUMN IF NOT EXISTS offset_unit text DEFAULT 'horas',
  ADD COLUMN IF NOT EXISTS total_duration_min_value numeric,
  ADD COLUMN IF NOT EXISTS total_duration_max_value numeric,
  ADD COLUMN IF NOT EXISTS total_duration_unit text DEFAULT 'horas',
  ADD COLUMN IF NOT EXISTS residual_min_value numeric,
  ADD COLUMN IF NOT EXISTS residual_max_value numeric,
  ADD COLUMN IF NOT EXISTS residual_unit text DEFAULT 'horas',
  ADD COLUMN IF NOT EXISTS dose_unit_default text,
  ADD COLUMN IF NOT EXISTS dose_low_min numeric,
  ADD COLUMN IF NOT EXISTS dose_low_max numeric,
  ADD COLUMN IF NOT EXISTS dose_usual_min numeric,
  ADD COLUMN IF NOT EXISTS dose_usual_max numeric,
  ADD COLUMN IF NOT EXISTS dose_high_min numeric,
  ADD COLUMN IF NOT EXISTS dose_high_max numeric,
  ADD COLUMN IF NOT EXISTS dose_max_recommended numeric,
  ADD COLUMN IF NOT EXISTS dose_notes text,
  ADD COLUMN IF NOT EXISTS titration_notes text,
  ADD COLUMN IF NOT EXISTS renal_adjustment_notes text,
  ADD COLUMN IF NOT EXISTS hepatic_adjustment_notes text,
  ADD COLUMN IF NOT EXISTS food_interaction_profile jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS food_delay_onset_minutes_min numeric,
  ADD COLUMN IF NOT EXISTS food_delay_onset_minutes_max numeric,
  ADD COLUMN IF NOT EXISTS food_effect_notes text,
  ADD COLUMN IF NOT EXISTS high_fat_meal_effect text,
  ADD COLUMN IF NOT EXISTS empty_stomach_effect text,
  ADD COLUMN IF NOT EXISTS caffeine_interaction_notes text,
  ADD COLUMN IF NOT EXISTS alcohol_interaction_notes text,
  ADD COLUMN IF NOT EXISTS sleep_deprivation_risk_notes text,
  ADD COLUMN IF NOT EXISTS cyp_substrate text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS cyp_inhibitor text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS cyp_inducer text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS ugt_substrate text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS ugt_inhibitor text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS ugt_inducer text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS transporter_substrate text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS transporter_inhibitor text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS interaction_rules jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS contraindication_rules jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS monitoring_rules jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS black_box_warnings text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS major_warnings text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS common_adverse_effects text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS serious_adverse_effects text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS cardiovascular_risk_level text,
  ADD COLUMN IF NOT EXISTS seizure_risk_level text,
  ADD COLUMN IF NOT EXISTS psychosis_mania_risk_level text,
  ADD COLUMN IF NOT EXISTS respiratory_depression_risk_level text,
  ADD COLUMN IF NOT EXISTS serotonin_syndrome_risk_level text,
  ADD COLUMN IF NOT EXISTS qt_risk_level text,
  ADD COLUMN IF NOT EXISTS metabolic_risk_level text,
  ADD COLUMN IF NOT EXISTS cognitive_impairment_risk_level text,
  ADD COLUMN IF NOT EXISTS sedation_risk_level text,
  ADD COLUMN IF NOT EXISTS insomnia_risk_level text,
  ADD COLUMN IF NOT EXISTS abuse_risk_level text,
  ADD COLUMN IF NOT EXISTS source_references jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS source_notes text,
  ADD COLUMN IF NOT EXISTS last_reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS reviewed_by text;

-- ============== CLINICAL SESSIONS ==============
ALTER TABLE public.clinical_sessions
  ADD COLUMN IF NOT EXISTS sleep_quality_0_10 integer,
  ADD COLUMN IF NOT EXISTS restorative_sleep_bool boolean,
  ADD COLUMN IF NOT EXISTS sleep_deprivation_level_0_10 integer,
  ADD COLUMN IF NOT EXISTS nightmares_0_10 integer,
  ADD COLUMN IF NOT EXISTS awakenings_count integer,
  ADD COLUMN IF NOT EXISTS baseline_mood_0_10 integer,
  ADD COLUMN IF NOT EXISTS baseline_anxiety_0_10 integer,
  ADD COLUMN IF NOT EXISTS baseline_irritability_0_10 integer,
  ADD COLUMN IF NOT EXISTS baseline_focus_0_10 integer,
  ADD COLUMN IF NOT EXISTS baseline_impulsivity_0_10 integer,
  ADD COLUMN IF NOT EXISTS baseline_craving_0_10 integer,
  ADD COLUMN IF NOT EXISTS basal_state_text text,
  ADD COLUMN IF NOT EXISTS cognitive_overload_0_10 integer,
  ADD COLUMN IF NOT EXISTS stress_0_10 integer,
  ADD COLUMN IF NOT EXISTS caffeine_total_mg numeric,
  ADD COLUMN IF NOT EXISTS alcohol_use_today boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS substance_use_today boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS psychosis_warning_signs boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS paranoia_0_10 integer,
  ADD COLUMN IF NOT EXISTS ideas_of_reference_0_10 integer,
  ADD COLUMN IF NOT EXISTS mania_activation_0_10 integer,
  ADD COLUMN IF NOT EXISTS notes text;

-- ============== MEDICATION DOSE LOGS ==============
ALTER TABLE public.medication_dose_logs
  ADD COLUMN IF NOT EXISTS stomach_fullness_0_10 integer,
  ADD COLUMN IF NOT EXISTS last_meal_time timestamptz,
  ADD COLUMN IF NOT EXISTS minutes_since_last_meal integer,
  ADD COLUMN IF NOT EXISTS meal_size text,
  ADD COLUMN IF NOT EXISTS meal_fat_level_0_10 integer,
  ADD COLUMN IF NOT EXISTS caffeine_near_dose_mg numeric,
  ADD COLUMN IF NOT EXISTS sleep_deprivation_at_dose_0_10 integer,
  ADD COLUMN IF NOT EXISTS benefit_0_100 integer,
  ADD COLUMN IF NOT EXISTS adverse_0_100 integer,
  ADD COLUMN IF NOT EXISTS sedation_0_100 integer,
  ADD COLUMN IF NOT EXISTS stimulation_0_100 integer,
  ADD COLUMN IF NOT EXISTS anxiety_0_100 integer,
  ADD COLUMN IF NOT EXISTS focus_0_100 integer,
  ADD COLUMN IF NOT EXISTS impulsivity_0_100 integer,
  ADD COLUMN IF NOT EXISTS craving_0_100 integer,
  ADD COLUMN IF NOT EXISTS notes_patient text,
  ADD COLUMN IF NOT EXISTS notes_clinician text;

-- ============== PATIENT SUBSTANCE RESPONSE PROFILES ==============
CREATE TABLE IF NOT EXISTS public.patient_substance_response_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  substance_id uuid,
  substance_name text NOT NULL,
  sample_count integer NOT NULL DEFAULT 0,
  average_benefit_0_100 numeric,
  average_adverse_0_100 numeric,
  average_sedation_0_100 numeric,
  average_stimulation_0_100 numeric,
  average_anxiety_0_100 numeric,
  average_focus_0_100 numeric,
  average_impulsivity_change_0_100 numeric,
  average_craving_change_0_100 numeric,
  typical_onset_shift_minutes numeric,
  typical_duration_shift_minutes numeric,
  food_sensitivity_0_100 numeric,
  caffeine_sensitivity_0_100 numeric,
  sleep_deprivation_sensitivity_0_100 numeric,
  redose_risk_0_100 numeric,
  psychosis_activation_risk_0_100 numeric,
  confidence text DEFAULT 'baixa',
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(patient_id, substance_name)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.patient_substance_response_profiles TO authenticated;
GRANT ALL ON public.patient_substance_response_profiles TO service_role;

ALTER TABLE public.patient_substance_response_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "owner manages response profiles"
  ON public.patient_substance_response_profiles
  FOR ALL
  USING (auth.uid() = owner_id)
  WITH CHECK (auth.uid() = owner_id);

CREATE TRIGGER set_updated_at_response_profiles
  BEFORE UPDATE ON public.patient_substance_response_profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
